// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repositories

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Couple struct {
	ID        uuid.UUID   `json:"id"`
	User1ID   *uuid.UUID  `json:"user1_id"`
	User2ID   *uuid.UUID  `json:"user2_id"`
	StartDate pgtype.Date `json:"start_date"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type User struct {
	ID             uuid.UUID   `json:"id"`
	Username       string      `json:"username"`
	Email          string      `json:"email"`
	HashedPassword string      `json:"hashed_password"`
	DisplayName    string      `json:"display_name"`
	BirthDay       pgtype.Date `json:"birth_day"`
	Gender         string      `json:"gender"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}
