// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repositories

import (
	"context"
)

type Querier interface {
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	RevokeToken(ctx context.Context, arg RevokeTokenParams) error
}

var _ Querier = (*Queries)(nil)
