// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_token.sql

package repositories

import (
	"context"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (family_id, user_id, token_hash)
    VALUES ($1, $2, $3)
RETURNING
    id, user_id, token_hash, family_id, is_revoked, created_at, expired_at
`

type CreateRefreshTokenParams struct {
	FamilyID  uuid.UUID `json:"family_id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.FamilyID, arg.UserID, arg.TokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE
    refresh_tokens
SET
    is_revoked = TRUE
WHERE
    id = $1
    AND token_hash = $2
`

type RevokeTokenParams struct {
	ID        uuid.UUID `json:"id"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.Exec(ctx, revokeToken, arg.ID, arg.TokenHash)
	return err
}
