// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package repositories

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, hashed_password, display_name, birth_day, gender)
    VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, username, email, hashed_password, display_name, birth_day, gender, created_at, updated_at
`

type CreateUserParams struct {
	Username       string      `json:"username"`
	Email          string      `json:"email"`
	HashedPassword string      `json:"hashed_password"`
	DisplayName    string      `json:"display_name"`
	BirthDay       pgtype.Date `json:"birth_day"`
	Gender         string      `json:"gender"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.HashedPassword,
		arg.DisplayName,
		arg.BirthDay,
		arg.Gender,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.DisplayName,
		&i.BirthDay,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
